networks:
  porto-net:
    driver: bridge

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - porto-net
    depends_on:
      - ms-mesas
      - ms-empleados
      - ms-infraestructura
      - ms-inventario
      - ms-orden-bar
      - ms-orden-cocina
      - ms-pedidos
      - ms-reservas
      - ms-catalogo

  ms-mesas:
    build: ./ms-mesas
    container_name: ms-mesas
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://reseau.proxy.rlwy.net:27822/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=aCienoMPmTWFdbxaUppGQYHKUTBkZxNo
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=2
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
      - MS_INFRAESTRUCTURA_HOST=ms-infraestructura
      - MS_INVENTARIO_HOST=ms-inventario
    networks:
      - porto-net

  ms-inventario:
    build: ./ms-inventario
    container_name: ms-inventario
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://reseau.proxy.rlwy.net:27822/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=aCienoMPmTWFdbxaUppGQYHKUTBkZxNo
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=2
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
    networks:
      - porto-net

  ms-infraestructura:
    build: ./ms-infraestructura
    container_name: ms-infraestructura
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://reseau.proxy.rlwy.net:27822/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=aCienoMPmTWFdbxaUppGQYHKUTBkZxNo
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=2
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
    networks:
      - porto-net

  ms-empleados:
    build: ./ms-empleados
    container_name: ms-empleados
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://reseau.proxy.rlwy.net:27822/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=aCienoMPmTWFdbxaUppGQYHKUTBkZxNo
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=2
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
    networks:
      - porto-net

  ms-catalogo:
    build: ./ms-catalogo
    container_name: ms-catalogo
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://reseau.proxy.rlwy.net:27822/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=aCienoMPmTWFdbxaUppGQYHKUTBkZxNo
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=2
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
    networks:
      - porto-net

  ms-pedidos:
    build: ./ms-pedidos
    container_name: ms-pedidos
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://reseau.proxy.rlwy.net:27822/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=aCienoMPmTWFdbxaUppGQYHKUTBkZxNo
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=2
      - MS_EMPLEADOS_HOST=ms-empleados
      - MS_INVENTARIO_HOST=ms-inventario
      - MS_COCINA_HOST=ms-orden-cocina
      - MS_BAR_HOST=ms-orden-bar
      - MS_CATALOGO_HOST=ms-catalogo
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
    networks:
      - porto-net

  ms-orden-cocina:
    build: ./ms-orden-cocina
    container_name: ms-orden-cocina
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://reseau.proxy.rlwy.net:27822/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=aCienoMPmTWFdbxaUppGQYHKUTBkZxNo
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=2
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
    networks:
      - porto-net

  ms-orden-bar:
    build: ./ms-orden-bar
    container_name: ms-orden-bar
    ports:
      - "9090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://reseau.proxy.rlwy.net:27822/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=aCienoMPmTWFdbxaUppGQYHKUTBkZxNo
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=2
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
    networks:
      - porto-net

  ms-reservas:
    build: ./ms-reservas
    container_name: ms-reservas
    ports:
      - "8091:8091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://reseau.proxy.rlwy.net:27822/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=aCienoMPmTWFdbxaUppGQYHKUTBkZxNo
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=2
      - MS_CLIENTES_HOST=https://ms-clientes-production-ddc2.up.railway.app
      - MS_MESAS_HOST=http://ms-mesas:8081
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
    networks:
      - porto-net