server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      x-forwarded:
        prefix-enabled: false
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        # ==========================================
        # RUTAS DE TRAFICO DE APIS (Logica de Negocio)
        # ==========================================
        # --- NUBE (RAILWAY) ---
        - id: route-ms-clientes
          uri: https://ms-clientes-production-ddc2.up.railway.app
          predicates:
            - Path=/api/clientes/**

        # --- LOCALES (DOCKER) ---
        - id: route-ms-mesas
          uri: http://ms-mesas:8081
          predicates:
            - Path=/api/mesas/**
          filters:
            - PreserveHostHeader

        - id: route-ms-inventario
          uri: http://ms-inventario:8083
          predicates:
            - Path=/api/inventario/**
          filters:
            - PreserveHostHeader

        - id: route-ms-infraestructura
          uri: http://ms-infraestructura:8085
          predicates:
            - Path=/api/infraestructura/**
          filters:
            - PreserveHostHeader

        - id: route-ms-empleados
          uri: http://ms-empleados:8086
          predicates:
            - Path=/api/empleados/**
          filters:
            - PreserveHostHeader

        - id: route-ms-catalogo
          uri: http://ms-catalogo:8087
          predicates:
            - Path=/api/catalogo/**
          filters:
            - PreserveHostHeader

        - id: route-ms-pedidos
          uri: http://ms-pedidos:8088
          predicates:
            - Path=/api/pedidos/**
          filters:
            - PreserveHostHeader

        - id: route-ms-orden-cocina
          uri: http://ms-orden-cocina:8089
          predicates:
            - Path=/api/cocina/**
          filters:
            - PreserveHostHeader

        - id: route-ms-orden-bar
          uri: http://ms-orden-bar:8090
          predicates:
            - Path=/api/bar/**
          filters:
            - PreserveHostHeader

        - id: route-ms-reservas
          uri: http://ms-reservas:8091
          predicates:
            - Path=/api/reservas/**
          filters:
            - PreserveHostHeader

        # ==========================================
        # RUTAS DE EXTRACCION DE DOCS SWAGGER
        # ==========================================
        # --- NUBE (RAILWAY) ---
        - id: docs-clientes
          uri: https://ms-clientes-production-ddc2.up.railway.app
          predicates:
            - Path=/docs-clientes/**
          filters:
            - RewritePath=/docs-clientes/(?<segment>.*), /$\{segment}

        # --- LOCALES (DOCKER) ---
        - id: docs-mesas
          uri: http://ms-mesas:8081
          predicates:
            - Path=/docs-mesas/**
          filters:
            - RewritePath=/docs-mesas/(?<segment>.*), /$\{segment}
            - PreserveHostHeader

        - id: docs-inventario
          uri: http://ms-inventario:8083
          predicates:
            - Path=/docs-inventario/**
          filters:
            - RewritePath=/docs-inventario/(?<segment>.*), /$\{segment}
            - PreserveHostHeader

        - id: docs-infraestructura
          uri: http://ms-infraestructura:8085
          predicates:
            - Path=/docs-infraestructura/**
          filters:
            - RewritePath=/docs-infraestructura/(?<segment>.*), /$\{segment}
            - PreserveHostHeader

        - id: docs-empleados
          uri: http://ms-empleados:8086
          predicates:
            - Path=/docs-empleados/**
          filters:
            - RewritePath=/docs-empleados/(?<segment>.*), /$\{segment}
            - PreserveHostHeader

        - id: docs-catalogo
          uri: http://ms-catalogo:8087
          predicates:
            - Path=/docs-catalogo/**
          filters:
            - RewritePath=/docs-catalogo/(?<segment>.*), /$\{segment}
            - PreserveHostHeader

        - id: docs-pedidos
          uri: http://ms-pedidos:8088
          predicates:
            - Path=/docs-pedidos/**
          filters:
            - RewritePath=/docs-pedidos/(?<segment>.*), /$\{segment}
            - PreserveHostHeader

        - id: docs-cocina
          uri: http://ms-orden-cocina:8089
          predicates:
            - Path=/docs-cocina/**
          filters:
            - RewritePath=/docs-cocina/(?<segment>.*), /$\{segment}
            - PreserveHostHeader

        - id: docs-bar
          uri: http://ms-orden-bar:8090
          predicates:
            - Path=/docs-bar/**
          filters:
            - RewritePath=/docs-bar/(?<segment>.*), /$\{segment}
            - PreserveHostHeader

        - id: docs-reservas
          uri: http://ms-reservas:8091
          predicates:
            - Path=/docs-reservas/**
          filters:
            - RewritePath=/docs-reservas/(?<segment>.*), /$\{segment}
            - PreserveHostHeader

# --- CONFIGURACION DEL SUPER SWAGGER ---
springdoc:
  swagger-ui:
    urls:
      - name: API Clientes
        url: /docs-clientes/v3/api-docs
      - name: API Mesas
        url: /docs-mesas/v3/api-docs
      - name: API Inventario
        url: /docs-inventario/v3/api-docs
      - name: API Infraestructura
        url: /docs-infraestructura/v3/api-docs
      - name: API Empleados
        url: /docs-empleados/v3/api-docs
      - name: API Catalogo
        url: /docs-catalogo/v3/api-docs
      - name: API Pedidos
        url: /docs-pedidos/v3/api-docs
      - name: API Cocina
        url: /docs-cocina/v3/api-docs
      - name: API Bar
        url: /docs-bar/v3/api-docs
      - name: API Reservas
        url: /docs-reservas/v3/api-docs